-- Generated from src/lib/curated.ts by `npm run seed`. Don't edit by hand.
-- Loads NeetCode 150, with the Blind 75 problems marked, into the catalog.
-- Safe to run again: existing rows (including ones you logged yourself) are
-- updated in place, so your progress on them is kept.

insert into problems (slug, title, url, difficulty, topics, in_blind75, in_neetcode150, list_order, created_by) values
  ('contains-duplicate', 'Contains Duplicate', 'https://leetcode.com/problems/contains-duplicate/', 'easy', '{arrays-hashing}', true, true, 1, null),
  ('valid-anagram', 'Valid Anagram', 'https://leetcode.com/problems/valid-anagram/', 'easy', '{arrays-hashing}', true, true, 2, null),
  ('two-sum', 'Two Sum', 'https://leetcode.com/problems/two-sum/', 'easy', '{arrays-hashing}', true, true, 3, null),
  ('group-anagrams', 'Group Anagrams', 'https://leetcode.com/problems/group-anagrams/', 'medium', '{arrays-hashing}', true, true, 4, null),
  ('top-k-frequent-elements', 'Top K Frequent Elements', 'https://leetcode.com/problems/top-k-frequent-elements/', 'medium', '{arrays-hashing}', true, true, 5, null),
  ('encode-and-decode-strings', 'Encode and Decode Strings', 'https://leetcode.com/problems/encode-and-decode-strings/', 'medium', '{arrays-hashing}', true, true, 6, null),
  ('product-of-array-except-self', 'Product of Array Except Self', 'https://leetcode.com/problems/product-of-array-except-self/', 'medium', '{arrays-hashing}', true, true, 7, null),
  ('valid-sudoku', 'Valid Sudoku', 'https://leetcode.com/problems/valid-sudoku/', 'medium', '{arrays-hashing}', false, true, 8, null),
  ('longest-consecutive-sequence', 'Longest Consecutive Sequence', 'https://leetcode.com/problems/longest-consecutive-sequence/', 'medium', '{arrays-hashing}', true, true, 9, null),
  ('valid-palindrome', 'Valid Palindrome', 'https://leetcode.com/problems/valid-palindrome/', 'easy', '{two-pointers}', true, true, 10, null),
  ('two-sum-ii-input-array-is-sorted', 'Two Sum II - Input Array Is Sorted', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', 'medium', '{two-pointers}', false, true, 11, null),
  ('3sum', '3Sum', 'https://leetcode.com/problems/3sum/', 'medium', '{two-pointers}', true, true, 12, null),
  ('container-with-most-water', 'Container With Most Water', 'https://leetcode.com/problems/container-with-most-water/', 'medium', '{two-pointers}', true, true, 13, null),
  ('trapping-rain-water', 'Trapping Rain Water', 'https://leetcode.com/problems/trapping-rain-water/', 'hard', '{two-pointers}', false, true, 14, null),
  ('best-time-to-buy-and-sell-stock', 'Best Time to Buy and Sell Stock', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'easy', '{sliding-window}', true, true, 15, null),
  ('longest-substring-without-repeating-characters', 'Longest Substring Without Repeating Characters', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'medium', '{sliding-window}', true, true, 16, null),
  ('longest-repeating-character-replacement', 'Longest Repeating Character Replacement', 'https://leetcode.com/problems/longest-repeating-character-replacement/', 'medium', '{sliding-window}', true, true, 17, null),
  ('permutation-in-string', 'Permutation in String', 'https://leetcode.com/problems/permutation-in-string/', 'medium', '{sliding-window}', false, true, 18, null),
  ('minimum-window-substring', 'Minimum Window Substring', 'https://leetcode.com/problems/minimum-window-substring/', 'hard', '{sliding-window}', true, true, 19, null),
  ('sliding-window-maximum', 'Sliding Window Maximum', 'https://leetcode.com/problems/sliding-window-maximum/', 'hard', '{sliding-window}', false, true, 20, null),
  ('valid-parentheses', 'Valid Parentheses', 'https://leetcode.com/problems/valid-parentheses/', 'easy', '{stack}', true, true, 21, null),
  ('min-stack', 'Min Stack', 'https://leetcode.com/problems/min-stack/', 'medium', '{stack}', false, true, 22, null),
  ('evaluate-reverse-polish-notation', 'Evaluate Reverse Polish Notation', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', 'medium', '{stack}', false, true, 23, null),
  ('generate-parentheses', 'Generate Parentheses', 'https://leetcode.com/problems/generate-parentheses/', 'medium', '{stack}', false, true, 24, null),
  ('daily-temperatures', 'Daily Temperatures', 'https://leetcode.com/problems/daily-temperatures/', 'medium', '{stack}', false, true, 25, null),
  ('car-fleet', 'Car Fleet', 'https://leetcode.com/problems/car-fleet/', 'medium', '{stack}', false, true, 26, null),
  ('largest-rectangle-in-histogram', 'Largest Rectangle in Histogram', 'https://leetcode.com/problems/largest-rectangle-in-histogram/', 'hard', '{stack}', false, true, 27, null),
  ('binary-search', 'Binary Search', 'https://leetcode.com/problems/binary-search/', 'easy', '{binary-search}', false, true, 28, null),
  ('search-a-2d-matrix', 'Search a 2D Matrix', 'https://leetcode.com/problems/search-a-2d-matrix/', 'medium', '{binary-search}', false, true, 29, null),
  ('koko-eating-bananas', 'Koko Eating Bananas', 'https://leetcode.com/problems/koko-eating-bananas/', 'medium', '{binary-search}', false, true, 30, null),
  ('find-minimum-in-rotated-sorted-array', 'Find Minimum in Rotated Sorted Array', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 'medium', '{binary-search}', true, true, 31, null),
  ('search-in-rotated-sorted-array', 'Search in Rotated Sorted Array', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 'medium', '{binary-search}', true, true, 32, null),
  ('time-based-key-value-store', 'Time Based Key-Value Store', 'https://leetcode.com/problems/time-based-key-value-store/', 'medium', '{binary-search}', false, true, 33, null),
  ('median-of-two-sorted-arrays', 'Median of Two Sorted Arrays', 'https://leetcode.com/problems/median-of-two-sorted-arrays/', 'hard', '{binary-search}', false, true, 34, null),
  ('reverse-linked-list', 'Reverse Linked List', 'https://leetcode.com/problems/reverse-linked-list/', 'easy', '{linked-list}', true, true, 35, null),
  ('merge-two-sorted-lists', 'Merge Two Sorted Lists', 'https://leetcode.com/problems/merge-two-sorted-lists/', 'easy', '{linked-list}', true, true, 36, null),
  ('linked-list-cycle', 'Linked List Cycle', 'https://leetcode.com/problems/linked-list-cycle/', 'easy', '{linked-list}', true, true, 37, null),
  ('reorder-list', 'Reorder List', 'https://leetcode.com/problems/reorder-list/', 'medium', '{linked-list}', true, true, 38, null),
  ('remove-nth-node-from-end-of-list', 'Remove Nth Node From End of List', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 'medium', '{linked-list}', true, true, 39, null),
  ('copy-list-with-random-pointer', 'Copy List With Random Pointer', 'https://leetcode.com/problems/copy-list-with-random-pointer/', 'medium', '{linked-list}', false, true, 40, null),
  ('add-two-numbers', 'Add Two Numbers', 'https://leetcode.com/problems/add-two-numbers/', 'medium', '{linked-list}', false, true, 41, null),
  ('find-the-duplicate-number', 'Find the Duplicate Number', 'https://leetcode.com/problems/find-the-duplicate-number/', 'medium', '{linked-list}', false, true, 42, null),
  ('lru-cache', 'LRU Cache', 'https://leetcode.com/problems/lru-cache/', 'medium', '{linked-list}', false, true, 43, null),
  ('merge-k-sorted-lists', 'Merge k Sorted Lists', 'https://leetcode.com/problems/merge-k-sorted-lists/', 'hard', '{linked-list}', true, true, 44, null),
  ('reverse-nodes-in-k-group', 'Reverse Nodes in k-Group', 'https://leetcode.com/problems/reverse-nodes-in-k-group/', 'hard', '{linked-list}', false, true, 45, null),
  ('invert-binary-tree', 'Invert Binary Tree', 'https://leetcode.com/problems/invert-binary-tree/', 'easy', '{trees}', true, true, 46, null),
  ('maximum-depth-of-binary-tree', 'Maximum Depth of Binary Tree', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'easy', '{trees}', true, true, 47, null),
  ('diameter-of-binary-tree', 'Diameter of Binary Tree', 'https://leetcode.com/problems/diameter-of-binary-tree/', 'easy', '{trees}', false, true, 48, null),
  ('balanced-binary-tree', 'Balanced Binary Tree', 'https://leetcode.com/problems/balanced-binary-tree/', 'easy', '{trees}', false, true, 49, null),
  ('same-tree', 'Same Tree', 'https://leetcode.com/problems/same-tree/', 'easy', '{trees}', true, true, 50, null),
  ('subtree-of-another-tree', 'Subtree of Another Tree', 'https://leetcode.com/problems/subtree-of-another-tree/', 'easy', '{trees}', true, true, 51, null),
  ('lowest-common-ancestor-of-a-binary-search-tree', 'Lowest Common Ancestor of a Binary Search Tree', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'medium', '{trees}', true, true, 52, null),
  ('binary-tree-level-order-traversal', 'Binary Tree Level Order Traversal', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 'medium', '{trees}', true, true, 53, null),
  ('binary-tree-right-side-view', 'Binary Tree Right Side View', 'https://leetcode.com/problems/binary-tree-right-side-view/', 'medium', '{trees}', false, true, 54, null),
  ('count-good-nodes-in-binary-tree', 'Count Good Nodes in Binary Tree', 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', 'medium', '{trees}', false, true, 55, null),
  ('validate-binary-search-tree', 'Validate Binary Search Tree', 'https://leetcode.com/problems/validate-binary-search-tree/', 'medium', '{trees}', true, true, 56, null),
  ('kth-smallest-element-in-a-bst', 'Kth Smallest Element in a BST', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 'medium', '{trees}', true, true, 57, null),
  ('construct-binary-tree-from-preorder-and-inorder-traversal', 'Construct Binary Tree from Preorder and Inorder Traversal', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 'medium', '{trees}', true, true, 58, null),
  ('binary-tree-maximum-path-sum', 'Binary Tree Maximum Path Sum', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', 'hard', '{trees}', true, true, 59, null),
  ('serialize-and-deserialize-binary-tree', 'Serialize and Deserialize Binary Tree', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 'hard', '{trees}', true, true, 60, null),
  ('implement-trie-prefix-tree', 'Implement Trie (Prefix Tree)', 'https://leetcode.com/problems/implement-trie-prefix-tree/', 'medium', '{tries}', true, true, 61, null),
  ('design-add-and-search-words-data-structure', 'Design Add and Search Words Data Structure', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', 'medium', '{tries}', true, true, 62, null),
  ('word-search-ii', 'Word Search II', 'https://leetcode.com/problems/word-search-ii/', 'hard', '{tries}', true, true, 63, null),
  ('kth-largest-element-in-a-stream', 'Kth Largest Element in a Stream', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', 'easy', '{heap}', false, true, 64, null),
  ('last-stone-weight', 'Last Stone Weight', 'https://leetcode.com/problems/last-stone-weight/', 'easy', '{heap}', false, true, 65, null),
  ('k-closest-points-to-origin', 'K Closest Points to Origin', 'https://leetcode.com/problems/k-closest-points-to-origin/', 'medium', '{heap}', false, true, 66, null),
  ('kth-largest-element-in-an-array', 'Kth Largest Element in an Array', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 'medium', '{heap}', false, true, 67, null),
  ('task-scheduler', 'Task Scheduler', 'https://leetcode.com/problems/task-scheduler/', 'medium', '{heap}', false, true, 68, null),
  ('design-twitter', 'Design Twitter', 'https://leetcode.com/problems/design-twitter/', 'medium', '{heap}', false, true, 69, null),
  ('find-median-from-data-stream', 'Find Median from Data Stream', 'https://leetcode.com/problems/find-median-from-data-stream/', 'hard', '{heap}', true, true, 70, null),
  ('subsets', 'Subsets', 'https://leetcode.com/problems/subsets/', 'medium', '{backtracking}', false, true, 71, null),
  ('combination-sum', 'Combination Sum', 'https://leetcode.com/problems/combination-sum/', 'medium', '{backtracking}', true, true, 72, null),
  ('permutations', 'Permutations', 'https://leetcode.com/problems/permutations/', 'medium', '{backtracking}', false, true, 73, null),
  ('subsets-ii', 'Subsets II', 'https://leetcode.com/problems/subsets-ii/', 'medium', '{backtracking}', false, true, 74, null),
  ('combination-sum-ii', 'Combination Sum II', 'https://leetcode.com/problems/combination-sum-ii/', 'medium', '{backtracking}', false, true, 75, null),
  ('word-search', 'Word Search', 'https://leetcode.com/problems/word-search/', 'medium', '{backtracking}', true, true, 76, null),
  ('palindrome-partitioning', 'Palindrome Partitioning', 'https://leetcode.com/problems/palindrome-partitioning/', 'medium', '{backtracking}', false, true, 77, null),
  ('letter-combinations-of-a-phone-number', 'Letter Combinations of a Phone Number', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', 'medium', '{backtracking}', false, true, 78, null),
  ('n-queens', 'N-Queens', 'https://leetcode.com/problems/n-queens/', 'hard', '{backtracking}', false, true, 79, null),
  ('number-of-islands', 'Number of Islands', 'https://leetcode.com/problems/number-of-islands/', 'medium', '{graphs}', true, true, 80, null),
  ('clone-graph', 'Clone Graph', 'https://leetcode.com/problems/clone-graph/', 'medium', '{graphs}', true, true, 81, null),
  ('max-area-of-island', 'Max Area of Island', 'https://leetcode.com/problems/max-area-of-island/', 'medium', '{graphs}', false, true, 82, null),
  ('pacific-atlantic-water-flow', 'Pacific Atlantic Water Flow', 'https://leetcode.com/problems/pacific-atlantic-water-flow/', 'medium', '{graphs}', true, true, 83, null),
  ('surrounded-regions', 'Surrounded Regions', 'https://leetcode.com/problems/surrounded-regions/', 'medium', '{graphs}', false, true, 84, null),
  ('rotting-oranges', 'Rotting Oranges', 'https://leetcode.com/problems/rotting-oranges/', 'medium', '{graphs}', false, true, 85, null),
  ('walls-and-gates', 'Walls and Gates', 'https://leetcode.com/problems/walls-and-gates/', 'medium', '{graphs}', false, true, 86, null),
  ('course-schedule', 'Course Schedule', 'https://leetcode.com/problems/course-schedule/', 'medium', '{graphs}', true, true, 87, null),
  ('course-schedule-ii', 'Course Schedule II', 'https://leetcode.com/problems/course-schedule-ii/', 'medium', '{graphs}', false, true, 88, null),
  ('redundant-connection', 'Redundant Connection', 'https://leetcode.com/problems/redundant-connection/', 'medium', '{graphs}', false, true, 89, null),
  ('number-of-connected-components-in-an-undirected-graph', 'Number of Connected Components in an Undirected Graph', 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 'medium', '{graphs}', true, true, 90, null),
  ('graph-valid-tree', 'Graph Valid Tree', 'https://leetcode.com/problems/graph-valid-tree/', 'medium', '{graphs}', true, true, 91, null),
  ('word-ladder', 'Word Ladder', 'https://leetcode.com/problems/word-ladder/', 'hard', '{graphs}', false, true, 92, null),
  ('network-delay-time', 'Network Delay Time', 'https://leetcode.com/problems/network-delay-time/', 'medium', '{advanced-graphs}', false, true, 93, null),
  ('min-cost-to-connect-all-points', 'Min Cost to Connect All Points', 'https://leetcode.com/problems/min-cost-to-connect-all-points/', 'medium', '{advanced-graphs}', false, true, 94, null),
  ('cheapest-flights-within-k-stops', 'Cheapest Flights Within K Stops', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', 'medium', '{advanced-graphs}', false, true, 95, null),
  ('reconstruct-itinerary', 'Reconstruct Itinerary', 'https://leetcode.com/problems/reconstruct-itinerary/', 'hard', '{advanced-graphs}', false, true, 96, null),
  ('swim-in-rising-water', 'Swim in Rising Water', 'https://leetcode.com/problems/swim-in-rising-water/', 'hard', '{advanced-graphs}', false, true, 97, null),
  ('alien-dictionary', 'Alien Dictionary', 'https://leetcode.com/problems/alien-dictionary/', 'hard', '{advanced-graphs}', true, true, 98, null),
  ('climbing-stairs', 'Climbing Stairs', 'https://leetcode.com/problems/climbing-stairs/', 'easy', '{1d-dp}', true, true, 99, null),
  ('min-cost-climbing-stairs', 'Min Cost Climbing Stairs', 'https://leetcode.com/problems/min-cost-climbing-stairs/', 'easy', '{1d-dp}', false, true, 100, null),
  ('house-robber', 'House Robber', 'https://leetcode.com/problems/house-robber/', 'medium', '{1d-dp}', true, true, 101, null),
  ('house-robber-ii', 'House Robber II', 'https://leetcode.com/problems/house-robber-ii/', 'medium', '{1d-dp}', true, true, 102, null),
  ('longest-palindromic-substring', 'Longest Palindromic Substring', 'https://leetcode.com/problems/longest-palindromic-substring/', 'medium', '{1d-dp}', true, true, 103, null),
  ('palindromic-substrings', 'Palindromic Substrings', 'https://leetcode.com/problems/palindromic-substrings/', 'medium', '{1d-dp}', true, true, 104, null),
  ('decode-ways', 'Decode Ways', 'https://leetcode.com/problems/decode-ways/', 'medium', '{1d-dp}', true, true, 105, null),
  ('coin-change', 'Coin Change', 'https://leetcode.com/problems/coin-change/', 'medium', '{1d-dp}', true, true, 106, null),
  ('maximum-product-subarray', 'Maximum Product Subarray', 'https://leetcode.com/problems/maximum-product-subarray/', 'medium', '{1d-dp}', true, true, 107, null),
  ('word-break', 'Word Break', 'https://leetcode.com/problems/word-break/', 'medium', '{1d-dp}', true, true, 108, null),
  ('longest-increasing-subsequence', 'Longest Increasing Subsequence', 'https://leetcode.com/problems/longest-increasing-subsequence/', 'medium', '{1d-dp}', true, true, 109, null),
  ('partition-equal-subset-sum', 'Partition Equal Subset Sum', 'https://leetcode.com/problems/partition-equal-subset-sum/', 'medium', '{1d-dp}', false, true, 110, null),
  ('unique-paths', 'Unique Paths', 'https://leetcode.com/problems/unique-paths/', 'medium', '{2d-dp}', true, true, 111, null),
  ('longest-common-subsequence', 'Longest Common Subsequence', 'https://leetcode.com/problems/longest-common-subsequence/', 'medium', '{2d-dp}', true, true, 112, null),
  ('best-time-to-buy-and-sell-stock-with-cooldown', 'Best Time to Buy and Sell Stock with Cooldown', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', 'medium', '{2d-dp}', false, true, 113, null),
  ('coin-change-ii', 'Coin Change II', 'https://leetcode.com/problems/coin-change-ii/', 'medium', '{2d-dp}', false, true, 114, null),
  ('target-sum', 'Target Sum', 'https://leetcode.com/problems/target-sum/', 'medium', '{2d-dp}', false, true, 115, null),
  ('interleaving-string', 'Interleaving String', 'https://leetcode.com/problems/interleaving-string/', 'medium', '{2d-dp}', false, true, 116, null),
  ('edit-distance', 'Edit Distance', 'https://leetcode.com/problems/edit-distance/', 'medium', '{2d-dp}', false, true, 117, null),
  ('longest-increasing-path-in-a-matrix', 'Longest Increasing Path in a Matrix', 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', 'hard', '{2d-dp}', false, true, 118, null),
  ('distinct-subsequences', 'Distinct Subsequences', 'https://leetcode.com/problems/distinct-subsequences/', 'hard', '{2d-dp}', false, true, 119, null),
  ('burst-balloons', 'Burst Balloons', 'https://leetcode.com/problems/burst-balloons/', 'hard', '{2d-dp}', false, true, 120, null),
  ('regular-expression-matching', 'Regular Expression Matching', 'https://leetcode.com/problems/regular-expression-matching/', 'hard', '{2d-dp}', false, true, 121, null),
  ('maximum-subarray', 'Maximum Subarray', 'https://leetcode.com/problems/maximum-subarray/', 'medium', '{greedy}', true, true, 122, null),
  ('jump-game', 'Jump Game', 'https://leetcode.com/problems/jump-game/', 'medium', '{greedy}', true, true, 123, null),
  ('jump-game-ii', 'Jump Game II', 'https://leetcode.com/problems/jump-game-ii/', 'medium', '{greedy}', false, true, 124, null),
  ('gas-station', 'Gas Station', 'https://leetcode.com/problems/gas-station/', 'medium', '{greedy}', false, true, 125, null),
  ('hand-of-straights', 'Hand of Straights', 'https://leetcode.com/problems/hand-of-straights/', 'medium', '{greedy}', false, true, 126, null),
  ('merge-triplets-to-form-target-triplet', 'Merge Triplets to Form Target Triplet', 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/', 'medium', '{greedy}', false, true, 127, null),
  ('partition-labels', 'Partition Labels', 'https://leetcode.com/problems/partition-labels/', 'medium', '{greedy}', false, true, 128, null),
  ('valid-parenthesis-string', 'Valid Parenthesis String', 'https://leetcode.com/problems/valid-parenthesis-string/', 'medium', '{greedy}', false, true, 129, null),
  ('meeting-rooms', 'Meeting Rooms', 'https://leetcode.com/problems/meeting-rooms/', 'easy', '{intervals}', true, true, 130, null),
  ('insert-interval', 'Insert Interval', 'https://leetcode.com/problems/insert-interval/', 'medium', '{intervals}', true, true, 131, null),
  ('merge-intervals', 'Merge Intervals', 'https://leetcode.com/problems/merge-intervals/', 'medium', '{intervals}', true, true, 132, null),
  ('non-overlapping-intervals', 'Non-overlapping Intervals', 'https://leetcode.com/problems/non-overlapping-intervals/', 'medium', '{intervals}', true, true, 133, null),
  ('meeting-rooms-ii', 'Meeting Rooms II', 'https://leetcode.com/problems/meeting-rooms-ii/', 'medium', '{intervals}', true, true, 134, null),
  ('minimum-interval-to-include-each-query', 'Minimum Interval to Include Each Query', 'https://leetcode.com/problems/minimum-interval-to-include-each-query/', 'hard', '{intervals}', false, true, 135, null),
  ('happy-number', 'Happy Number', 'https://leetcode.com/problems/happy-number/', 'easy', '{math-geometry}', false, true, 136, null),
  ('plus-one', 'Plus One', 'https://leetcode.com/problems/plus-one/', 'easy', '{math-geometry}', false, true, 137, null),
  ('rotate-image', 'Rotate Image', 'https://leetcode.com/problems/rotate-image/', 'medium', '{math-geometry}', true, true, 138, null),
  ('spiral-matrix', 'Spiral Matrix', 'https://leetcode.com/problems/spiral-matrix/', 'medium', '{math-geometry}', true, true, 139, null),
  ('set-matrix-zeroes', 'Set Matrix Zeroes', 'https://leetcode.com/problems/set-matrix-zeroes/', 'medium', '{math-geometry}', true, true, 140, null),
  ('powx-n', 'Pow(x, n)', 'https://leetcode.com/problems/powx-n/', 'medium', '{math-geometry}', false, true, 141, null),
  ('multiply-strings', 'Multiply Strings', 'https://leetcode.com/problems/multiply-strings/', 'medium', '{math-geometry}', false, true, 142, null),
  ('detect-squares', 'Detect Squares', 'https://leetcode.com/problems/detect-squares/', 'medium', '{math-geometry}', false, true, 143, null),
  ('single-number', 'Single Number', 'https://leetcode.com/problems/single-number/', 'easy', '{bit-manipulation}', false, true, 144, null),
  ('number-of-1-bits', 'Number of 1 Bits', 'https://leetcode.com/problems/number-of-1-bits/', 'easy', '{bit-manipulation}', true, true, 145, null),
  ('counting-bits', 'Counting Bits', 'https://leetcode.com/problems/counting-bits/', 'easy', '{bit-manipulation}', true, true, 146, null),
  ('reverse-bits', 'Reverse Bits', 'https://leetcode.com/problems/reverse-bits/', 'easy', '{bit-manipulation}', true, true, 147, null),
  ('missing-number', 'Missing Number', 'https://leetcode.com/problems/missing-number/', 'easy', '{bit-manipulation}', true, true, 148, null),
  ('sum-of-two-integers', 'Sum of Two Integers', 'https://leetcode.com/problems/sum-of-two-integers/', 'medium', '{bit-manipulation}', true, true, 149, null),
  ('reverse-integer', 'Reverse Integer', 'https://leetcode.com/problems/reverse-integer/', 'medium', '{bit-manipulation}', false, true, 150, null)
on conflict (slug) do update set
  title = excluded.title,
  url = excluded.url,
  difficulty = excluded.difficulty,
  topics = excluded.topics,
  in_blind75 = excluded.in_blind75,
  in_neetcode150 = excluded.in_neetcode150,
  list_order = excluded.list_order;
